//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class HandPosMsgMsg : Message
    {
        public const string k_RosMessageName = "kinova_test/HandPosMsg";
        public override string RosMessageName => k_RosMessageName;

        public double[] hand_pos;
        public double[] hand_rot;

        public HandPosMsgMsg()
        {
            this.hand_pos = new double[3];
            this.hand_rot = new double[3];
        }

        public HandPosMsgMsg(double[] hand_pos, double[] hand_rot)
        {
            this.hand_pos = hand_pos;
            this.hand_rot = hand_rot;
        }

        public static HandPosMsgMsg Deserialize(MessageDeserializer deserializer) => new HandPosMsgMsg(deserializer);

        private HandPosMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.hand_pos, sizeof(double), 3);
            deserializer.Read(out this.hand_rot, sizeof(double), 3);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.hand_pos);
            serializer.Write(this.hand_rot);
        }

        public override string ToString()
        {
            return "HandPosMsgMsg: " +
            "\nhand_pos: " + System.String.Join(", ", hand_pos.ToList()) +
            "\nhand_rot: " + System.String.Join(", ", hand_rot.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
